[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "jupyterlite"
author = "JupyterLite Contributors"
home-page = "https://github.com/jtpio/jupyterlite"
description-file = "README.md"
requires = [
    "jupyter_core>=4.7.1,<5"
]

[tool.flit.scripts]
jupyter-lite = "jupyterlite.liteapp:main"